In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://gitlab.com/isnardynicolas/wcs_import/-/raw/main/tracks_features.csv")

In [3]:
# On récupère les types des valeurs des colonnes du data frame
def get_unique_column_types(df, col_name):
    """
    Returns a list of the unique types of values in the specified column of the DataFrame.

    Parameters:
    df (pandas.DataFrame): The DataFrame containing the column.
    col_name (str): The name of the column to check.

    Returns:
    list: A list of the unique types of values in the column.
    """
    unique_types = df[col_name].apply(type).unique()
    return unique_types

# List of column names in the DataFrame
column_names = df.columns.tolist()

# Iterate over each column name and print the unique types of values in that column
for col_name in column_names:
    types = get_unique_column_types(df, col_name)
    print(f"{col_name}' = {types}")

id' = [<class 'str'>]
name' = [<class 'str'>]
album' = [<class 'str'>]
album_id' = [<class 'str'>]
artists' = [<class 'str'>]
artist_ids' = [<class 'str'>]
track_number' = [<class 'int'>]
disc_number' = [<class 'int'>]
explicit' = [<class 'bool'>]
danceability' = [<class 'float'>]
energy' = [<class 'float'>]
key' = [<class 'int'>]
loudness' = [<class 'float'>]
mode' = [<class 'int'>]
speechiness' = [<class 'float'>]
acousticness' = [<class 'float'>]
instrumentalness' = [<class 'float'>]
liveness' = [<class 'float'>]
valence' = [<class 'float'>]
tempo' = [<class 'float'>]
duration_ms' = [<class 'int'>]
time_signature' = [<class 'float'>]
year' = [<class 'int'>]
release_date' = [<class 'str'>]

In [4]:
df.nunique()

id                  1204025
name                 850944
album                106162
album_id             118382
artists              165365
artist_ids           166423
track_number             50
disc_number              13
explicit                  2
danceability           1362
energy                 3441
key                      12
loudness              39805
mode                      2
speechiness            1653
acousticness           5398
instrumentalness       5402
liveness               1799
valence                1884
tempo                140472
duration_ms          210013
time_signature            5
year                    101
release_date          10566
dtype: int64

In [5]:
# On change une valeur abérante de la colonne release_date
df.loc[df.release_date == "0000", "release_date"] = "2018-09-04"

In [6]:
# On change une valeur abérante de la colonne year
df.loc[df.year == 0, "year"] = 2018

In [7]:
# Vérification 
print((df.release_date == "0000").sum())
print((df.year == 0).sum())

0
0

In [8]:
# Conversion de la colonne year en date_time
df.year = pd.to_datetime(df.year, format=  "%Y")

In [9]:
## Creation d'une copie pour éviter les bétises
df_copy = df.copy()

In [10]:
# On sélectionne les colonnes pertinantes
df_copy = df_copy[['id', 'name', 'album', 'album_id', 'artists', 'artist_ids',
       'explicit', 'danceability', 'energy',
       'loudness', 'speechiness',
       'valence', 'tempo', 'duration_ms',
       'year']]

In [11]:
# Création d'un masque des durées de musique supérieure à 10 min 
mask = df_copy.duration_ms > 600000
# On ne garde que les lignes qui ne sont pas dans le masque
df_copy = df_copy[~mask]

In [12]:
def nettoyage(artist):
    return artist.replace("[", "").replace("]", "")

df_copy.artists = df_copy.artists.apply(nettoyage)

In [13]:
df_copy

,id,name,album,album_id,artists,artist_ids,explicit,danceability,energy,loudness,speechiness,valence,tempo,duration_ms,year
0,7lmeHLHBe4nmXzuXc0HDjk,Testify,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,'Rage Against The Machine',['2d0hyoQ5ynDBnkvAbJKORj'],False,0.470,0.978,-5.399,0.0727,0.503,117.906,210133,1999-01-01
1,1wsRitfRRtWyEapl0q22o8,Guerrilla Radio,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,'Rage Against The Machine',['2d0hyoQ5ynDBnkvAbJKORj'],True,0.599,0.957,-5.764,0.1880,0.489,103.680,206200,1999-01-01
2,1hR0fIFK2qRG3f3RF70pb7,Calm Like a Bomb,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,'Rage Against The Machine',['2d0hyoQ5ynDBnkvAbJKORj'],False,0.315,0.970,-5.424,0.4830,0.370,149.749,298893,1999-01-01
3,2lbASgTSoDO7MTuLAXlTW0,Mic Check,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,'Rage Against The Machine',['2d0hyoQ5ynDBnkvAbJKORj'],True,0.440,0.967,-5.830,0.2370,0.574,96.752,213640,1999-01-01
4,1MQTmpYOZ6fcMQc56Hdo7T,Sleep Now In the Fire,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,'Rage Against The Machine',['2d0hyoQ5ynDBnkvAbJKORj'],False,0.426,0.929,-6.729,0.0701,0.539,127.059,205600,1999-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204020,0EsMifwUmMfJZxzoMPXJKZ,Gospel of Juke,Notch - EP,38O5Ys0W9PFS5K7dMb7yKb,'FVLCRVM',['7AjItKsRnEYRSiBt2OxK1y'],False,0.264,0.966,-6.970,0.0672,0.415,159.586,276213,2014-01-01
1204021,2WSc2TB1CSJgGE0PEzVeiu,Prism Visions,Notch - EP,38O5Ys0W9PFS5K7dMb7yKb,'FVLCRVM',['7AjItKsRnEYRSiBt2OxK1y'],False,0.796,0.701,-6.602,0.0883,0.781,121.980,363179,2014-01-01
1204022,6iProIgUe3ETpO6UT0v5Hg,Tokyo 360,Notch - EP,38O5Ys0W9PFS5K7dMb7yKb,'FVLCRVM',['7AjItKsRnEYRSiBt2OxK1y'],False,0.785,0.796,-5.960,0.0564,0.467,121.996,385335,2014-01-01
1204023,37B4SXC8uoBsUyKCWnhPfX,Yummy!,Notch - EP,38O5Ys0W9PFS5K7dMb7yKb,'FVLCRVM',['7AjItKsRnEYRSiBt2OxK1y'],False,0.665,0.856,-6.788,0.0409,0.227,124.986,324455,2014-01-01
1204024,3GgQmOxxLyRoAb4j86zOBX,That's The Way It Is,Notch - EP,38O5Ys0W9PFS5K7dMb7yKb,'FVLCRVM',['7AjItKsRnEYRSiBt2OxK1y'],False,0.736,0.708,-9.279,0.0539,0.204,117.991,304982,2014-01-01

In [20]:
# On exporte au format csv
df_copy.to_csv("/content/sample_data/datathonbbq.csv")

In [21]:
df_copy.loc[(df.name.str.contains("Thunder"))]

,id,name,album,album_id,artists,artist_ids,explicit,danceability,energy,loudness,speechiness,valence,tempo,duration_ms,year
1132,3EOTqLimBnBQPSx1FbSQ9w,Thunder Dreamer - Timewave Mix,Groove Tribe,4Arv2qXssKmDhOxKW9pUcO,'David & Steve Gordon',['4yt002Vil1q4Vl9JOx48QG'],False,0.769,0.849,-10.378,0.0393,0.7020,124.005,285302,2011-01-01
1991,66hjtaVBwgqnaLCSVZBbwg,Thunderstorm,In Reverse,6eW8RSaJVFcCgV7DuLWVan,'Matthew Sweet',['2idymNTKUdnTxforkb12Mw'],False,0.270,0.665,-6.969,0.0441,0.3620,100.422,577773,1999-01-01
2308,7rB3NJ9E3XVLJSs78LCM4l,Thunderdome,Reforged,2XxqVEbpSvDGo2J3PqFDVg,'Zephaniah',['7JZhOvH58gTVYLaX5WOVwR'],False,0.266,0.970,-3.836,0.1120,0.2850,90.084,290149,2016-01-01
3689,1OU0yG9QKkFflastCoyttJ,Southern Thunder,Stormy,0RpjVT5m7uCwjcMlvy7K47,"'Hank Williams, Jr.'",['2dyeCWctcFRt3Pha76ONgb'],False,0.636,0.793,-3.770,0.0299,0.5790,93.015,300493,1999-01-01
5339,34qaHht7RWN0c1dTj4OGKd,Thunderbird ESQ,The Shaw Tapes: Live In Detroit 5/27/88,4zBL0rHt9dTxOghha5O94D,'The Gories',['5tcr1ujTO3Q0WH2wkY7RWh'],False,0.591,0.861,-8.047,0.0467,0.7930,92.365,150413,2013-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1193179,0gspEP4FV26P0ftTintsHb,Thunder,Ears Wide Shut,3Syfmr4LIs7Ubn9z9JrzCi,'The A-Bones',['1HJKMokVRiiUSsjfubhtKq'],False,0.248,0.807,-8.276,0.0447,0.6400,156.669,179053,2014-01-01
1193670,1rClkLqOH3vNroWCFUAJdV,Thunderforce,Juggernaut's Wrath 2,00jsLpp6VXQpcXzU1hP5Gt,'Revolt Production Music',['5aYAUA8CBgKOAhAmjEg9ra'],False,0.358,0.913,-9.280,0.0627,0.1010,149.932,158857,2016-01-01
1195184,0Rj994GUgsxbCeBzNxAC4m,I Am the Thunder,Cyberblade,0ql0CrhFAGBMpNHp0u43km,'Shadow Warrior',['77J5B6M4wJesuY3QDKjGUI'],False,0.588,0.976,-8.028,0.0842,0.0396,119.950,268513,2020-01-01
1200634,1yF5Du14fgtCvokdNyhdVP,Storming The Thunder,The Cosmic Waters (Inspired by 'The Outlaw Oce...,5euL6qFngzBF3uEXB8AnhV,"'Televangel', 'Ian Urbina'","['2J6cJXIuA7tHufujlMnrKF', '7miGJahGF5JYOunptm...",False,0.573,0.558,-10.148,0.0305,0.1270,146.022,289315,2020-01-01
1203587,1fHvDqHHT8U3wOYQydUZVC,Thunder and Lightning,Hoffnung,409B6xss45zK9olos5z8P6,'Lacrimosa',['57ekbx9PSS4ORs5wTZMSYp'],False,0.513,0.891,-6.107,0.0707,0.3780,125.991,235413,2015-01-01